# Generated by Django 4.2.5 on 2024-07-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiaPrima', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaprima',
            name='descricao',
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='disponivel',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='preco',
            field=models.FloatField(null=True),
        ),
    ]
