# Generated by Django 4.2.5 on 2024-07-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_materias_primas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.AddField(
            model_name='produto',
            name='precoVenda',
            field=models.FloatField(null=True),
        ),
    ]
